# Used in development

services:
  evaluator:
    build: .
    privileged: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RUN_WITH_CGROUPS=true
      - RUN_WITH_QUOTAS=false
      - FORCE_DEBUG_LOGS=true
      # expects local redis
      - REDIS_URL=redis://host.docker.internal:6379

